### ISSUE TITLE
NPE on empty <artifacts> block

### ISSUE THREAD

**Issue by akhayrutdinov** [igor-suhorukov/aspectj-scripting#2]
When XML configuration is used, empty `<artifacts>` section causes error:

```
2015/11/17 07:27:39 - General - Caused by: java.lang.NullPointerException
2015/11/17 07:27:39 - General -         at java.util.regex.Matcher.getTextLength(Matcher.java:1234)
2015/11/17 07:27:39 - General -         at java.util.regex.Matcher.reset(Matcher.java:308)
2015/11/17 07:27:39 - General -         at java.util.regex.Matcher.<init>(Matcher.java:228)
2015/11/17 07:27:39 - General -         at java.util.regex.Pattern.matcher(Pattern.java:1088)
2015/11/17 07:27:39 - General -         at org.sonatype.aether.util.artifact.DefaultArtifact.<init>(DefaultArtifact.java:70)
2015/11/17 07:27:39 - General -         at org.sonatype.aether.util.artifact.DefaultArtifact.<init>(DefaultArtifact.java:56)
2015/11/17 07:27:39 - General -         at com.github.smreed.dropship.MavenClassLoader$ClassLoaderBuilder.createCollectRequestForGAV(MavenClassLoader.java:82)
2015/11/17 07:27:39 - General -         at com.github.smreed.dropship.MavenClassLoader$ClassLoaderBuilder.forMavenCoordinates(MavenClassLoader.java:59)
2015/11/17 07:27:39 - General -         at org.aspectj.util.MavenLoader.getClassLoader(MavenLoader.java:36)
2015/11/17 07:27:39 - General -         at org.aspectj.util.MavenLoader.loadArtifact(MavenLoader.java:66)
2015/11/17 07:27:39 - General -         at org.aspectj.aspect.lifecycle.BaseAspectLifecycle.<init>(BaseAspectLifecycle.java:38)
2015/11/17 07:27:39 - General -         at org.aspectj.aspect.AbstractBeforeAspect.<init>(AbstractBeforeAspect.java:13)
```

After `<artifacts/>` has been removed, everything went fine.

**Comment by igor-suhorukov** [comment]
Thanks for report!
Bug fixed in com.github.igor-suhorukov:aspectj-scripting:1.1

**Comment by igor-suhorukov** [comment]
http://central.maven.org/maven2/com/github/igor-suhorukov/aspectj-scripting/1.1/aspectj-scripting-1.1-agent.jar
